<div class="jumbotron">
<img src="<?php echo $this->basePath('img/slide.png') ?>" alt="Zend Framework 2"/>&nbsp;
</div>
<?php 
$listCollection = $this->listCollection;

?>
<div class="row">
		<?php foreach ($listCollection as $val) { ?>
		<div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $val['c_name'] ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
     <?php }?>
        
        
</div>
